global:
  sendAnonymousUsage: false

api:
  dashboard: true
#  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
  file:
    filename: /etc/traefik/config.yml
    watch: true

log:
  level: INFO
  format: common
## Writing Logs to a File, in JSON
#log:
#  level: DEBUG
#  filePath: "log-file.log"
#  format: json
#
## Configuring a buffer of 100 lines
#accessLog:
#  filePath: "log-access.log"
#  bufferingSize: 100

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  metrics:
    address: ":8000"

metrics:
  prometheus:
    entryPoint: metrics

certificatesResolvers:
  letsEncrypt:
    acme:
      # comment this line when going to production
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: jean.pommier@pi-geosolutions.fr
      storage: /acme/acme.json
      httpChallenge:
        entryPoint: web
